### ISSUE TITLE
Use offical pretested integration jobdsl support instead of configure block

### ISSUE THREAD

**Issue by Andrey9kin** [Praqma/JenkinsAsCodeReference#1]

**Comment by alexsedova** [comment]
Investigated. We could use Pretested Integration Extension but we will not be ably to test it with set up we have now. It will work on the real environment, I mean in Jenkins. To test the extension we need to create JobManagment object that provides by JenkinsInstance in runtime. Because of we run BuildXML task locally we are not able to use real instances. As a workaround we could redefine javaposse.jobdsl.Run class to generate items and be able to use CallExtension to call Pretested Integration. But I don't see a point to do it, now we are using configure block and it works. If we will use the extension we will have to extend the project for two more classes and rewrite build.gradle.

**Comment by ewelinawilkosz2** [comment]
if we work on #7 we can move this one to this new repository

**Comment by ewelinawilkosz2** [comment]
moved to https://github.com/Praqma/jobdsl-helpers/issues/1
