### ISSUE TITLE
DSL syntax for Logstash Plugin

### ISSUE THREAD

**Issue by amruthapbhat** [Praqma/JenkinsAsCodeReference#198]
Hi,

I have an exciting dsl scipt where in i would to add " Send console logs to Logstash" which is in general a post build action. 

Could you please let me know if there is a way i could incorporate as part of a DSL job?

**Comment by amruthapbhat** [comment]
Could anyone let me know if this is a feature which is being supported?

**Comment by Andrey9kin** [comment]
@amruthapbhat I'm not sure that I understand your question. Are you asking how to configure JobDSL snippet to generate job that will send logs to logstash?

**Comment by amruthapbhat** [comment]
@Andrey9kin Yes. I want to send the console output log to logstash as my post build action

**Comment by Andrey9kin** [comment]
@amruthapbhat Alright. Well, this is not really related to this repository but I can help with your question anyway.

As far as I can see currently this plugin is not supported by JobDSL. Otherwise, you wouldn't ask, right? :) So, in such cases, you can use configure block https://github.com/jenkinsci/job-dsl-plugin/wiki/The-Configure-Block

Do it this way. First, create a job in UI and configure it as you want it. Then, add /config.xml to your job URL - it will show you actual XML file which represents your job on the disk. Look for the section that corresponds to logstash post-build (it should be in publishers section). Then when you know how XML should look like you can describe it using configure block

I hope it helps! Let me know if you have more questions
