### ISSUE TITLE
Add clean up job

### ISSUE THREAD

**Issue by Andrey9kin** [Praqma/JenkinsAsCodeReference#31]
We need to clean old containers and images

**Comment by Andrey9kin** [comment]
Make sure that we remove old images, layers and so on in order to avoid running out of space on the docker host

**Comment by Andrey9kin** [comment]
https://www.brianchristner.io/docker-cleanup-script-comparison/

**Comment by alexsedova** [comment]
- The job will be triggered by Jenkins. Every night will do. It doesn't have to be a part of the pipeline
- I will leave this choice to you. Important thing that we understand what is going on so we can document this behaviour for users

**Comment by alexsedova** [comment]
One more thing we need to clarify. Because of we are mapping docker socket, docker commands will be executed directly on docker host, as well as all layers images and containers and so on will store there, am I correct? If so, we don't need to be care about labels and slaves, because docker clean up will run docker out of docker.

**Comment by Andrey9kin** [comment]
@alexsedova it could be so that we will have multiple slaves running on different hosts so consider making generic solution

**Comment by alexsedova** [comment]
@Andrey9kin My suggestion using NodeLabel Parameter plugin to run docker clean up job on every node labeled as a docker host, for example. To do clean up I'm using docker-clean tool, see https://github.com/zzrotdesign/docker-clean . "docker-clean images" command removes all tagged and untagged images aren't associated with running containers, stopped containers, dangling volumes, and networks. This command doesn't remove running containers and images these containers based on. I'm going to create dsl method in JobBuilder class. If I missed something important or forget some scenarios , please contact me.

**Comment by alexsedova** [comment]
@Andrey9kin @drBosse 
Watch the JenkinsIssues!
 Found the issue [JENKINS-33756](https://issues.jenkins-ci.org/browse/JENKINS-33756)
Job is run twice on first slave using label parameter. If the box "Run on all nodes matching the label"
is checked, the job will be triggered twice in the node it has been started. For example,
If we have 4 slaves are matching one label, we will have 5 running jobs instead of 4.
These issue is not resolved yet.
We don't use cluster of docker hosts, that is why we are running job on
all slaves matching "docker" label even they are running on the one host. We could run
clean up job just once, while we don't have a multihost cluster - it is another
possible solution. In this case we will not get the issue with double job running.
