### ISSUE TITLE
Remove unreadable data from jenkins as a code review

### ISSUE THREAD

**Issue by drBosse** [Praqma/JenkinsAsCodeReference#78]

**Comment by drBosse** [comment]
![screen shot 2016-06-20 at 13 23 10](https://cloud.githubusercontent.com/assets/9803106/16192593/80c235b0-36ea-11e6-8f85-671ac7e7028f.png)

**Comment by Andrey9kin** [comment]
Today we are using configure block to configure pretested
https://github.com/Praqma/JenkinsAsCodeReference/blob/master/jobdsl-gradle/src/main/groovy/job/JobBuilder.groovy

So we need to use official methods + update gradle build file to pull in pretested since DSL extension is included into the plugin itself not JobDSL

**Comment by ewelinawilkosz2** [comment]
once we remove review job this issue will be gone
